<?php

/**
 * This is the model base class for the table "trader".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Trader".
 *
 * Columns in table "trader" available as properties of the model,
 * followed by relations of table "trader" available as properties of the model.
 *
 * @property integer $id
 * @property string $firm
 * @property integer $contract
 * @property integer $rias
 * @property integer $some_from
 * @property integer $all_from
 * @property integer $nkhp
 * @property integer $is_nkhp
 * @property integer $is_nzt
 * @property string $shorts
 *
 * @property RequestShipping[] $requestShippings
 */
abstract class BaseTrader extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'trader';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Trader|Traders', $n);
	}

	public static function representingColumn() {
		return 'firm';
	}

	public function rules() {
		return array(
			array('firm, rias, some_from, all_from', 'required'),
			array('contract, rias, some_from, all_from, nkhp, is_nkhp, is_nzt', 'numerical', 'integerOnly'=>true),
			array('shorts', 'length', 'max'=>4),
			array('contract, nkhp, is_nkhp, is_nzt, shorts', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, firm, contract, rias, some_from, all_from, nkhp, is_nkhp, is_nzt, shorts', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'requestShippings' => array(self::HAS_MANY, 'RequestShipping', 'trader_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'firm' => Yii::t('app', 'Firm'),
			'contract' => Yii::t('app', 'Contract'),
			'rias' => Yii::t('app', 'Rias'),
			'some_from' => Yii::t('app', 'Some From'),
			'all_from' => Yii::t('app', 'All From'),
			'nkhp' => Yii::t('app', 'Nkhp'),
			'is_nkhp' => Yii::t('app', 'Is Nkhp'),
			'is_nzt' => Yii::t('app', 'Is Nzt'),
			'shorts' => Yii::t('app', 'Shorts'),
			'requestShippings' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('firm', $this->firm, true);
		$criteria->compare('contract', $this->contract);
		$criteria->compare('rias', $this->rias);
		$criteria->compare('some_from', $this->some_from);
		$criteria->compare('all_from', $this->all_from);
		$criteria->compare('nkhp', $this->nkhp);
		$criteria->compare('is_nkhp', $this->is_nkhp);
		$criteria->compare('is_nzt', $this->is_nzt);
		$criteria->compare('shorts', $this->shorts, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}