<?php

/**
 * This is the model base class for the table "orange_log".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "OrangeLog".
 *
 * Columns in table "orange_log" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $sessionId
 * @property integer $errorCode
 * @property string $dates
 * @property integer $type
 * @property string $plate
 *
 */
abstract class BaseOrangeLog extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'orange_log';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'OrangeLog|OrangeLogs', $n);
	}

	public static function representingColumn() {
		return 'sessionId';
	}

	public function rules() {
		return array(
			array('errorCode, type', 'numerical', 'integerOnly'=>true),
			array('sessionId', 'length', 'max'=>150),
			array('plate', 'length', 'max'=>25),
			array('dates', 'safe'),
			array('sessionId, errorCode, dates, type, plate', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, sessionId, errorCode, dates, type, plate', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'sessionId' => Yii::t('app', 'Session'),
			'errorCode' => Yii::t('app', 'Error Code'),
			'dates' => Yii::t('app', 'Dates'),
			'type' => Yii::t('app', 'Type'),
			'plate' => Yii::t('app', 'Plate'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('sessionId', $this->sessionId, true);
		$criteria->compare('errorCode', $this->errorCode);
		$criteria->compare('dates', $this->dates, true);
		$criteria->compare('type', $this->type);
		$criteria->compare('plate', $this->plate, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}