<?php

/**
 * This is the model base class for the table "trader".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Trader".
 *
 * Columns in table "trader" available as properties of the model,
 * followed by relations of table "trader" available as properties of the model.
 *
 * @property integer $id
 * @property string $firm
 * @property integer $status
 *
 * @property RequestShipping[] $requestShippings
 */
abstract class BaseTrader extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'trader';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Trader|Traders', $n);
	}

	public static function representingColumn() {
		return 'firm';
	}

	public function rules() {
		return array(
			array('firm', 'required'),
			array('status', 'numerical', 'integerOnly'=>true),
			array('status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, firm, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'requestShippings' => array(self::HAS_MANY, 'RequestShipping', 'trader_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'firm' => Yii::t('app', 'Firm'),
			'status' => Yii::t('app', 'Status'),
			'requestShippings' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('firm', $this->firm, true);
		$criteria->compare('status', $this->status);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}