<?php

/**
 * This is the model base class for the table "z_report".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ZReport".
 *
 * Columns in table "z_report" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $int
 * @property string $date
 * @property string $comment
 * @property integer $z_report
 * @property integer $fact_amount
 * @property integer $count_payment
 *
 */
abstract class BaseZReport extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'z_report';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ZReport|ZReports', $n);
	}

	public static function representingColumn() {
		return 'date';
	}

	public function rules() {
		return array(
			array('date, comment, z_report', 'required'),
			array('z_report, fact_amount, count_payment', 'numerical', 'integerOnly'=>true),
			array('fact_amount, count_payment', 'default', 'setOnEmpty' => true, 'value' => null),
			array('int, date, comment, z_report, fact_amount, count_payment', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'int' => Yii::t('app', 'Int'),
			'date' => Yii::t('app', 'Date'),
			'comment' => Yii::t('app', 'Comment'),
			'z_report' => Yii::t('app', 'Z Report'),
			'fact_amount' => Yii::t('app', 'Fact Amount'),
			'count_payment' => Yii::t('app', 'Count Payment'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('int', $this->int);
		$criteria->compare('date', $this->date, true);
		$criteria->compare('comment', $this->comment, true);
		$criteria->compare('z_report', $this->z_report);
		$criteria->compare('fact_amount', $this->fact_amount);
		$criteria->compare('count_payment', $this->count_payment);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}