<?php

/**
 * This is the model base class for the table "reply_shipping".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ReplyShipping".
 *
 * Columns in table "reply_shipping" available as properties of the model,
 * followed by relations of table "reply_shipping" available as properties of the model.
 *
 * @property string $id
 * @property integer $user_id
 * @property integer $request_id
 * @property string $date_create
 * @property integer $trucks_count
 * @property string $price
 * @property integer $confirm
 *
 * @property Users $user
 * @property RequestShipping $request
 */
abstract class BaseReplyShipping extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'reply_shipping';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ReplyShipping|ReplyShippings', $n);
	}

	public static function representingColumn() {
		return 'date_create';
	}

	public function rules() {
		return array(
			array('user_id, date_create, price', 'required'),
			array('user_id, request_id, trucks_count, confirm', 'numerical', 'integerOnly'=>true),
			array('price', 'length', 'max'=>10),
			array('request_id, trucks_count, confirm', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, request_id, date_create, trucks_count, price, confirm', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'Users', 'user_id'),
			'request' => array(self::BELONGS_TO, 'RequestShipping', 'request_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'request_id' => null,
			'date_create' => Yii::t('app', 'Date Create'),
			'trucks_count' => Yii::t('app', 'Trucks Count'),
			'price' => Yii::t('app', 'Price'),
			'confirm' => Yii::t('app', 'Confirm'),
			'user' => null,
			'request' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('request_id', $this->request_id);
		$criteria->compare('date_create', $this->date_create, true);
		$criteria->compare('trucks_count', $this->trucks_count);
		$criteria->compare('price', $this->price, true);
		$criteria->compare('confirm', $this->confirm);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}