<?php

/**
 * This is the model base class for the table "socrbase".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Socrbase".
 *
 * Columns in table "socrbase" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $LEVEL
 * @property string $SCNAME
 * @property string $SOCRNAME
 * @property string $KOD_T_ST
 *
 */
abstract class BaseSocrbase extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'socrbase';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Socrbase|Socrbases', $n);
	}

	public static function representingColumn() {
		return 'LEVEL';
	}

	public function rules() {
		return array(
			array('LEVEL', 'length', 'max'=>5),
			array('SCNAME', 'length', 'max'=>10),
			array('SOCRNAME', 'length', 'max'=>29),
			array('KOD_T_ST', 'length', 'max'=>3),
			array('LEVEL, SCNAME, SOCRNAME, KOD_T_ST', 'default', 'setOnEmpty' => true, 'value' => null),
			array('LEVEL, SCNAME, SOCRNAME, KOD_T_ST', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'LEVEL' => Yii::t('app', 'Level'),
			'SCNAME' => Yii::t('app', 'Scname'),
			'SOCRNAME' => Yii::t('app', 'Socrname'),
			'KOD_T_ST' => Yii::t('app', 'Kod T St'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('LEVEL', $this->LEVEL, true);
		$criteria->compare('SCNAME', $this->SCNAME, true);
		$criteria->compare('SOCRNAME', $this->SOCRNAME, true);
		$criteria->compare('KOD_T_ST', $this->KOD_T_ST, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}