<?php

/**
 * This is the model base class for the table "rating".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Rating".
 *
 * Columns in table "rating" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $description
 * @property string $rating
 * @property integer $user_id_create
 * @property integer $user_type_create
 * @property integer $user_id_for
 * @property integer $user_type_for
 * @property string $date_create
 * @property integer $delete
 *
 */
abstract class BaseRating extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'rating';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Rating|Ratings', $n);
	}

	public static function representingColumn() {
		return 'description';
	}

	public function rules() {
		return array(
			array('description, rating, user_id_create, user_id_for, user_type_for', 'required'),
			array('user_id_create, user_type_create, user_id_for, user_type_for, delete', 'numerical', 'integerOnly'=>true),
			array('rating', 'length', 'max'=>3),
			array('date_create', 'safe'),
			array('user_type_create, date_create, delete', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, description, rating, user_id_create, user_type_create, user_id_for, user_type_for, date_create, delete', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'description' => Yii::t('app', 'Description'),
			'rating' => Yii::t('app', 'Rating'),
			'user_id_create' => Yii::t('app', 'User Id Create'),
			'user_type_create' => Yii::t('app', 'User Type Create'),
			'user_id_for' => Yii::t('app', 'User Id For'),
			'user_type_for' => Yii::t('app', 'User Type For'),
			'date_create' => Yii::t('app', 'Date Create'),
			'delete' => Yii::t('app', 'Delete'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('rating', $this->rating, true);
		$criteria->compare('user_id_create', $this->user_id_create);
		$criteria->compare('user_type_create', $this->user_type_create);
		$criteria->compare('user_id_for', $this->user_id_for);
		$criteria->compare('user_type_for', $this->user_type_for);
		$criteria->compare('date_create', $this->date_create, true);
		$criteria->compare('delete', $this->delete);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}