<?php

/**
 * This is the model base class for the table "load_type".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "LoadType".
 *
 * Columns in table "load_type" available as properties of the model,
 * followed by relations of table "load_type" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 *
 * @property RequestShipping[] $requestShippings
 */
abstract class BaseLoadType extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'load_type';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'LoadType|LoadTypes', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, description', 'required'),
			array('name', 'length', 'max'=>255),
			array('id, name, description', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'requestShippings' => array(self::HAS_MANY, 'RequestShipping', 'load_type_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'description' => Yii::t('app', 'Description'),
			'requestShippings' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('description', $this->description, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}