<?php

/**
 * This is the model base class for the table "culture".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Culture".
 *
 * Columns in table "culture" available as properties of the model,
 * followed by relations of table "culture" available as properties of the model.
 *
 * @property integer $id
 * @property string $culture
 * @property integer $nkhp
 * @property integer $receiver
 *
 * @property RequestShipping[] $requestShippings
 */
abstract class BaseCulture extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'culture';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Culture|Cultures', $n);
	}

	public static function representingColumn() {
		return 'culture';
	}

	public function rules() {
		return array(
			array('culture, nkhp', 'required'),
			array('nkhp, receiver', 'numerical', 'integerOnly'=>true),
			array('receiver', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, culture, nkhp, receiver', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'requestShippings' => array(self::HAS_MANY, 'RequestShipping', 'culure_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'culture' => Yii::t('app', 'Culture'),
			'nkhp' => Yii::t('app', 'Nkhp'),
			'receiver' => Yii::t('app', 'Receiver'),
			'requestShippings' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('culture', $this->culture, true);
		$criteria->compare('nkhp', $this->nkhp);
		$criteria->compare('receiver', $this->receiver);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}