<?php

/**
 * This is the model base class for the table "reply_shipping".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ReplyShipping".
 *
 * Columns in table "reply_shipping" available as properties of the model,
 * followed by relations of table "reply_shipping" available as properties of the model.
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $plate
 * @property string $date_create
 * @property integer $max_load
 * @property integer $request_id
 *
 * @property Truck $plate0
 * @property RequestShipping $request
 */
abstract class BaseReplyShipping extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'reply_shipping';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ReplyShipping|ReplyShippings', $n);
	}

	public static function representingColumn() {
		return 'date_create';
	}

	public function rules() {
		return array(
			array('id, user_id, plate, date_create, max_load', 'required'),
			array('id, user_id, max_load, request_id', 'numerical', 'integerOnly'=>true),
			array('plate', 'length', 'max'=>15),
			array('request_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, plate, date_create, max_load, request_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'plate0' => array(self::BELONGS_TO, 'Truck', 'plate'),
			'request' => array(self::BELONGS_TO, 'RequestShipping', 'request_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => Yii::t('app', 'User'),
			'plate' => null,
			'date_create' => Yii::t('app', 'Date Create'),
			'max_load' => Yii::t('app', 'Max Load'),
			'request_id' => null,
			'plate0' => null,
			'request' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('plate', $this->plate);
		$criteria->compare('date_create', $this->date_create, true);
		$criteria->compare('max_load', $this->max_load);
		$criteria->compare('request_id', $this->request_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}