<?php

/**
 * This is the model base class for the table "truck".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Truck".
 *
 * Columns in table "truck" available as properties of the model,
 * followed by relations of table "truck" available as properties of the model.
 *
 * @property integer $id
 * @property string $plate
 * @property string $rating
 * @property string $contact
 * @property integer $glonass_id
 *
 * @property ReplyShipping[] $replyShippings
 */
abstract class BaseTruck extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'truck';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Truck|Trucks', $n);
	}

	public static function representingColumn() {
		return 'rating';
	}

	public function rules() {
		return array(
			array('id, plate, contact', 'required'),
			array('id, glonass_id', 'numerical', 'integerOnly'=>true),
			array('plate', 'length', 'max'=>15),
			array('rating', 'length', 'max'=>3),
			array('rating, glonass_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, plate, rating, contact, glonass_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'replyShippings' => array(self::HAS_MANY, 'ReplyShipping', 'plate'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'plate' => Yii::t('app', 'Plate'),
			'rating' => Yii::t('app', 'Rating'),
			'contact' => Yii::t('app', 'Contact'),
			'glonass_id' => Yii::t('app', 'Glonass'),
			'replyShippings' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('plate', $this->plate, true);
		$criteria->compare('rating', $this->rating, true);
		$criteria->compare('contact', $this->contact, true);
		$criteria->compare('glonass_id', $this->glonass_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}