<?php

/**
 * This is the model base class for the table "stevedore".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Stevedore".
 *
 * Columns in table "stevedore" available as properties of the model,
 * followed by relations of table "stevedore" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $address
 * @property integer $regionUnloadId
 *
 * @property RequestShipping[] $requestShippings
 * @property RegionUnload $regionUnload
 */
abstract class BaseStevedore extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'stevedore';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Stevedore|Stevedores', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, address, regionUnloadId', 'required'),
			array('regionUnloadId', 'numerical', 'integerOnly'=>true),
			array('id, name, address, regionUnloadId', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'requestShippings' => array(self::HAS_MANY, 'RequestShipping', 'stividor_id'),
			'regionUnload' => array(self::BELONGS_TO, 'RegionUnload', 'regionUnloadId'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'address' => Yii::t('app', 'Address'),
			'regionUnloadId' => null,
			'requestShippings' => null,
			'regionUnload' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('address', $this->address, true);
		$criteria->compare('regionUnloadId', $this->regionUnloadId);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}