<?php

/**
 * This is the model base class for the table "status".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Status".
 *
 * Columns in table "status" available as properties of the model,
 * followed by relations of table "status" available as properties of the model.
 *
 * @property integer $id
 * @property string $name_for_all
 * @property string $name_for_admin
 *
 * @property RequestShipping[] $requestShippings
 */
abstract class BaseStatus extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'status';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Status|Statuses', $n);
	}

	public static function representingColumn() {
		return 'name_for_all';
	}

	public function rules() {
		return array(
			array('name_for_all, name_for_admin', 'required'),
			array('name_for_all, name_for_admin', 'length', 'max'=>255),
			array('id, name_for_all, name_for_admin', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'requestShippings' => array(self::HAS_MANY, 'RequestShipping', 'status_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name_for_all' => Yii::t('app', 'Name For All'),
			'name_for_admin' => Yii::t('app', 'Name For Admin'),
			'requestShippings' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name_for_all', $this->name_for_all, true);
		$criteria->compare('name_for_admin', $this->name_for_admin, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}