<?php

/**
 * This is the model base class for the table "kladr".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Kladr".
 *
 * Columns in table "kladr" available as properties of the model,
 * followed by relations of table "kladr" available as properties of the model.
 *
 * @property string $NAME
 * @property string $SOCR
 * @property string $CODE
 * @property string $INDEX
 * @property string $GNINMB
 * @property string $UNO
 * @property string $OCATD
 * @property string $STATUS
 *
 * @property RequestShipping[] $requestShippings
 */
abstract class BaseKladr extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'kladr';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Kladr|Kladrs', $n);
	}

	public static function representingColumn() {
		return 'NAME';
	}

	public function rules() {
		return array(
			array('NAME', 'length', 'max'=>40),
			array('SOCR', 'length', 'max'=>10),
			array('CODE', 'length', 'max'=>13),
			array('INDEX', 'length', 'max'=>6),
			array('GNINMB, UNO', 'length', 'max'=>4),
			array('OCATD', 'length', 'max'=>11),
			array('STATUS', 'length', 'max'=>1),
			array('NAME, SOCR, CODE, INDEX, GNINMB, UNO, OCATD, STATUS', 'default', 'setOnEmpty' => true, 'value' => null),
			array('NAME, SOCR, CODE, INDEX, GNINMB, UNO, OCATD, STATUS', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'requestShippings' => array(self::HAS_MANY, 'RequestShipping', 'region_load_kladr_code'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'NAME' => Yii::t('app', 'Name'),
			'SOCR' => Yii::t('app', 'Socr'),
			'CODE' => Yii::t('app', 'Code'),
			'INDEX' => Yii::t('app', 'Index'),
			'GNINMB' => Yii::t('app', 'Gninmb'),
			'UNO' => Yii::t('app', 'Uno'),
			'OCATD' => Yii::t('app', 'Ocatd'),
			'STATUS' => Yii::t('app', 'Status'),
			'requestShippings' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('NAME', $this->NAME, true);
		$criteria->compare('SOCR', $this->SOCR, true);
		$criteria->compare('CODE', $this->CODE, true);
		$criteria->compare('INDEX', $this->INDEX, true);
		$criteria->compare('GNINMB', $this->GNINMB, true);
		$criteria->compare('UNO', $this->UNO, true);
		$criteria->compare('OCATD', $this->OCATD, true);
		$criteria->compare('STATUS', $this->STATUS, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}